import { config, library } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowAltCircleDown,
  faCheckCircle,
  faCopy,
  faEnvelope,
  faFile,
  faFileAlt,
  faFileArchive,
  faFileAudio,
  faFileCode,
  faFileExcel,
  faFileImage,
  faFilePdf,
  faFilePowerpoint,
  faFileVideo,
  faFileWord,
  faFlag,
  faFolder,
  faTrashAlt,
} from '@fortawesome/free-regular-svg-icons'
import { faMarkdown } from '@fortawesome/free-brands-svg-icons'
import {
  faAngleRight,
  faArrowLeft,
  faArrowRight,
  faBook,
  faCheck,
  faChevronCircleDown,
  faChevronDown,
  faCloud,
  faCopy as faCopySolid,
  faDownload,
  faExclamationCircle,
  faExclamationTriangle,
  faExternalLinkAlt,
  faFileDownload,
  faHome,
  faKey,
  faLanguage,
  faLink,
  faMinus,
  faMusic,
  faPen,
  faPlus,
  faSearch,
  faSignOutAlt,
  faTh,
  faThLarge,
  faThList,
  faUndo,
} from '@fortawesome/free-solid-svg-icons'

export { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

config.autoAddCss = false

library.add(
  faFileImage,
  faFilePdf,
  faFileWord,
  faFilePowerpoint,
  faFileExcel,
  faFileAudio,
  faFileVideo,
  faFileArchive,
  faFileCode,
  faFileAlt,
  faFile,
  faMarkdown,
  faFlag,
  faFolder,
  faMusic,
  faArrowLeft,
  faArrowRight,
  faAngleRight,
  faFileDownload,
  faCopy,
  faCopySolid,
  faPlus,
  faMinus,
  faDownload,
  faLink,
  faUndo,
  faBook,
  faArrowAltCircleDown,
  faKey,
  faTrashAlt,
  faSignOutAlt,
  faEnvelope,
  faCloud,
  faChevronCircleDown,
  faExternalLinkAlt,
  faExclamationCircle,
  faExclamationTriangle,
  faHome,
  faCheck,
  faCheckCircle,
  faSearch,
  faChevronDown,
  faTh,
  faThLarge,
  faThList,
  faLanguage,
  faPen,
)
